package com.helios.orchestrator.infrastructure;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.helios.orchestrator.core.DagValidator;
import com.helios.orchestrator.core.SynthesisResult;
import com.helios.orchestrator.core.ValidationResult;
import com.helios.orchestrator.core.WorkflowSynthesizer;
import com.helios.sdk.model.WorkflowDefinition;

import java.io.IOException;
import java.net.URI;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;
import java.time.Duration;
import java.util.List;
import java.util.Map;

public final class AnthropicWorkflowSynthesizer implements WorkflowSynthesizer {
    private final HttpClient httpClient;
    private final ObjectMapper mapper;
    private final DagValidator validator;
    private final String apiKey;
    private final String model;
    private final URI messagesUri;

    public AnthropicWorkflowSynthesizer(ObjectMapper mapper, DagValidator validator, String apiKey, String model, URI messagesUri) {
        if (apiKey == null || apiKey.isBlank()) {
            throw new IllegalArgumentException("ANTHROPIC_API_KEY is required for real LLM synthesis");
        }
        this.httpClient = HttpClient.newBuilder().connectTimeout(Duration.ofSeconds(10)).build();
        this.mapper = mapper;
        this.validator = validator;
        this.apiKey = apiKey;
        this.model = model;
        this.messagesUri = messagesUri;
    }

    @Override
    public SynthesisResult synthesize(String tenantId, String workflowName, String description) {
        try {
            String prompt = prompt(tenantId, workflowName, description);
            String requestJson = mapper.writeValueAsString(Map.of(
                    "model", model,
                    "max_tokens", 2048,
                    "temperature", 0,
                    "system", "You synthesize valid Helios workflow DAG JSON only. Return one JSON object with fields name, tenantId, steps.",
                    "messages", List.of(Map.of("role", "user", "content", prompt))
            ));

            HttpRequest request = HttpRequest.newBuilder(messagesUri)
                    .timeout(Duration.ofSeconds(30))
                    .header("content-type", "application/json")
                    .header("anthropic-version", "2023-06-01")
                    .header("x-api-key", apiKey)
                    .POST(HttpRequest.BodyPublishers.ofString(requestJson))
                    .build();

            HttpResponse<String> response = httpClient.send(request, HttpResponse.BodyHandlers.ofString());
            if (response.statusCode() < 200 || response.statusCode() >= 300) {
                throw new IllegalStateException("Anthropic synthesis failed with HTTP " + response.statusCode() + ": " + response.body());
            }

            String text = extractText(response.body());
            WorkflowDefinition definition = mapper.readValue(stripJsonFence(text), WorkflowDefinition.class);
            ValidationResult validation = validator.validate(definition);
            return new SynthesisResult(definition, validation, "Generated by Anthropic model " + model + " and validated by Helios DAG validator.");
        } catch (IOException exception) {
            throw new IllegalStateException("failed to parse Anthropic synthesis response", exception);
        } catch (InterruptedException exception) {
            Thread.currentThread().interrupt();
            throw new IllegalStateException("interrupted while calling Anthropic synthesis", exception);
        }
    }

    private String prompt(String tenantId, String workflowName, String description) {
        return """
                Convert the workflow description into this exact JSON shape:
                {
                  "name": "kebab-case-name",
                  "tenantId": "tenant",
                  "steps": [
                    {
                      "name": "kebab-case-step",
                      "taskType": "HTTP|GRPC|KAFKA_PRODUCE|NOOP|COMPENSATION",
                      "dependsOn": [],
                      "retryPolicy": {"maxAttempts": 1, "initialBackoffMillis": 0, "multiplier": 1.0},
                      "timeoutMillis": 30000,
                      "failureMode": "FAIL_WORKFLOW|IGNORE",
                      "compensationStep": null,
                      "input": {}
                    }
                  ]
                }
                Rules:
                - Return JSON only.
                - Use only listed taskType values.
                - Use dependency edges that form an acyclic graph.
                - Add compensation steps only when rollback is clearly requested.
                - Compensation steps must use taskType COMPENSATION and must not depend on normal steps.
                Tenant: %s
                Workflow name: %s
                Description: %s
                """.formatted(defaultValue(tenantId, "default"), defaultValue(workflowName, "ai-synthesized-workflow"), description);
    }

    private String extractText(String responseBody) throws IOException {
        JsonNode root = mapper.readTree(responseBody);
        JsonNode content = root.path("content");
        if (!content.isArray() || content.isEmpty()) {
            throw new IllegalStateException("Anthropic response contained no content blocks");
        }
        for (JsonNode block : content) {
            if ("text".equals(block.path("type").asText())) {
                return block.path("text").asText();
            }
        }
        throw new IllegalStateException("Anthropic response contained no text block");
    }

    private String stripJsonFence(String text) {
        String trimmed = text.trim();
        if (trimmed.startsWith("```")) {
            trimmed = trimmed.replaceFirst("^```(?:json)?\\s*", "");
            trimmed = trimmed.replaceFirst("\\s*```$", "");
        }
        return trimmed;
    }

    private String defaultValue(String value, String fallback) {
        return value == null || value.isBlank() ? fallback : value;
    }
}
